version: v1
type: rest
packageName: com.example.demo
groupId: com.example
description: IMDB API
name: imbdapi
db:
  type: postgresql
  ip: localhost
  port: 5432
  username: postgres
  password:
  dbname: pagila
