import java.io.FileOutputStream;
import java.io.FileWriter;
import java.util.Objects;
import java.util.Properties;

public class GenerateAppPropertiesTask {

    public void execute(Recipe recipe) {
        try {
            String propertiesFolder = recipe.getApp().getArtifactId() + "/application/src/main/resources/" ;

            //generate base
            Properties properties = new Properties();
            properties.put("spring.datasource.url", JdbcPropertyRule.getUrl(recipe.getApp().getDb()));
            properties.put("spring.datasource.username", "${DB_USERNAME}");
            properties.put("spring.datasource.password", "${DB_PASSWORD}");

            properties.store(new FileOutputStream(propertiesFolder + "/application.properties"), "Generated by Homi 0.1.1");

            if(Objects.nonNull(recipe.getApp().getEnvironments())) {
                properties = new Properties();
                for(String env : recipe.getApp().getEnvironments()) {
                    properties.store(new FileOutputStream(propertiesFolder + "/application-" + env + ".properties"), "Generated by Homi 0.1.1");
                }
            }
        }
        catch(Exception e) {
            throw new RuntimeException("Unable to load templates or write output.");
        }
    }
}
