id: product-service
name: product-service
version: 0.0.2
routes:
  - id: httpbin_ip
    uri: https://httpbin.org/
    predicates:
    - Path=/ip
    filters:
    - AddRequestHeader=X-Request-red, blue
  - id: httpbin_headers
    uri: https://httpbin.org/
    predicates:
      - Path=/headers
    filters:
    - AddRequestHeader=X-Request-COLOR, blue
