name: plankton-app
services:
  - name: product-service
    image:
      registry_type: DOCKER_HUB
      registry: homihq
      repository: product-service
      tag: latest
    instance_count: 1
    instance_size_slug: professional-xs
    internal_ports:
      - 8080
