app:
  packageName: com.homihq.event
  groupId: com.homihq.event
  artifactId: event-management-api
  description: Event Management API
  db: pg
  dbVersionManager : lb
  environments:
    - local
    - dev
    - stage
    - prod

dbConfig:
  schemaSelection:
    - matchCatalog: pg
      matchSchema: public
      matchTable: author
    - matchCatalog: pg
      matchSchema: public
      matchTable: article

  tableFilter:
    - match-catalog: "catalog_matching_rule"
      match-schema: "schema_matching_rule"
      match-name: "table_matching_rule"
      exclude: "true|false"
      package: "package.name"




