app:
  packageName: com.homihq.event
  groupId: com.homihq.event
  artifactId: event-management-api
  description: Event Management API
  db: pg
  dbVersionManager : lb
  environments:
    - local
    - dev
    - stage
    - prod

generator:
  schemaFilter:
    - author
  tableFilter:
    - flyway_schema_history
  table:
    - name: article
      schema: author
      primaryKey:
          - generator: identity
            column: id




