app:
  packageName: com.homihq.event
  groupId: com.homihq.event
  artifactId: event-management-api
  description: Event Management API
  db: pg
  dbVersionManager : lb
  environments:
    - local
    - dev
    - stage
    - prod






